
"use strict";
const HEADSHOT="https://www.adamgriffee.com/wp-content/uploads/2026/10/Adam-Griffee-Full-Headshot-scaled.jpg";
const PROPERTY="https://www.adamgriffee.com/wp-content/uploads/2026/10/7169-Canyon-Dr-Park-City-Utah-Exterior-26.jpg";
const ZEN="./properties-zen-logo.svg",Q="./q-logo.svg";
const organizations=[["zen","Properties Zen","#0d8177","Less Stress. More Home."],["adam","Adam Griffee Realtor","#c1a369","Luxury real estate command center"],["luxury","eXp Luxury Real Estate","#b49c66","Luxury real estate team"],["quality","Quality CRM","#276ac0","One Identity. Every Business."],["utrd","Utah Real Estate Directory","#29649f","MLS directory and education"],["iur","Inside Utah Real Estate","#36667a","Editorial & market intelligence"],["parkcity","Homes for Sale in Park City","#327c9c","Park City local marketing"],["dental","Quality Dental","#3593a3","Dental services"],["clm","Create Local Marketing","#b49b61","Agency and websites"]];
const menu=[["dashboard","table-cells-large","Dashboard"],["hot","fire-flame-curved","Hot Leads"],["leads","users","Leads"],["listings","house","Listings"],["transactions","arrows-rotate","Transactions"],["calendar","calendar-days","Calendar"],["tasks","list-check","Tasks"],["inbox","envelope","Inbox"],["marketing","bullhorn","Marketing"],["dialer","phone","Dialer"],["calls","chart-column","Call Dashboard"],["sms","comment-sms","SMS"],["documents","file-lines","Documents"],["websites","globe","Websites"],["reports","chart-line","Analytics"],["portal","mobile-screen","Client Experience"],["cards","address-card","Business Card"],["settings","gear","Settings"]];
const initialSteps=[
 ["Purchase contract accepted","Buyer & Seller","Agents","Signed agreement","Complete","All parties execute the contract, creating the transaction."],
 ["Earnest money deposited","Buyer","Title / Escrow","Deposit receipt","Complete","Deposit according to the executed contract and confirm receipt."],
 ["Seller disclosures","Seller","Buyer","Disclosure packet","Complete","Seller provides contractually required disclosures for buyer review."],
 ["Inspection / due diligence","Buyer & Inspector","Buyer Agent","Inspection report","Complete","Inspections and contingency review occur under contract deadlines."],
 ["Resolution and contingencies","Buyer & Seller","Agents","Amendments","Complete","Negotiations and contingency decisions are documented."],
 ["Loan processing","Buyer & Lender","Lender","Requested borrower documents","Complete","Borrower provides financial documents directly through a secure lender channel."],
 ["Appraisal","Lender / Appraiser","Lender","Appraisal milestone","Complete","Appraisal commissioned and reviewed as required by the financing."],
 ["Title commitment","Title / Escrow","Buyer / Agents","Commitment","Complete","Title commitment and exceptions are reviewed."],
 ["Insurance evidence","Buyer / Insurer","Lender","Insurance binder","Complete","Required insurance coverage is confirmed."],
 ["Final settlement figures","Title / Escrow","Lender / Agents","Settlement figures","Waiting","Title/escrow supplies final settlement figures; lender manages its disclosures independently."],
 ["Closing Disclosure review","Lender","Buyer","Closing Disclosure","Upcoming","Lender delivers required disclosures within applicable legal deadlines."],
 ["Final walkthrough and signing","Buyer / Seller / Title","Agents","Signing package","Upcoming","Walkthrough and signatures coordinated under the agreed closing schedule."],
 ["Funding, recording and possession","Title / Escrow","Buyer / Seller","Recording confirmation","Upcoming","Funding, recording, and key handoff follow contract terms."]
];
const people=[["Jamie Davis","Buyer","Review documents","JD"],["Taylor Davis","Seller","Cooperate on requests","TD"],["Adam Griffee","Realtor / Buyer Agent","Coordinate transaction","PHOTO"],["Listing Agent","Seller Agent","Coordinate seller handoffs","LA"],["Escrow Coordinator","Title Officer","Settlement figures pending","EC"],["Loan Officer","Lender","Review financing","LO"],["Insurance Advisor","Insurance","Proof of coverage","IA"],["Property Inspector","Inspector","Inspection completed","PI"]];
const comps=[["Example Comparable A · Park City",4780,2300000],["Example Comparable B · Park City",5120,2475000],["Example Comparable C · Park City",4650,2265000]];
const state={org:"zen",page:"dashboard",role:"agent",login:true,steps:JSON.parse(JSON.stringify(initialSteps)),tasks:[{t:"Review settlement figures",done:false},{t:"Send buyer milestone update",done:false},{t:"Confirm final walkthrough",done:true}],selected:[0,1,2],tab:"timeline",reports:[],draft:"",phone:""};
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function money(n){return "$"+Math.round(n).toLocaleString("en-US")}
function organization(){return organizations.find(x=>x[0]===state.org)||organizations[0]}
function logo(){return state.org==="zen"?ZEN:Q}
function badge(t){let cls=/Wait|Hot|Action/i.test(t)?" wait":/Upcoming|Pending|Process/i.test(t)?" blue":"";return '<span class="pill'+cls+'">'+esc(t)+'</span>'}
function fa(icon){return '<i class="fa-solid fa-'+icon+'" aria-hidden="true"></i>'}
function pic(){return '<img src="'+HEADSHOT+'" class="avatar" alt="Actual Adam Griffee headshot">'}
function row(title,detail,status,face){return '<div class="list-item">'+(face==="PHOTO"?pic():face?'<div class="initial">'+face+'</div>':'<span class="iconbox">'+fa("file-lines")+'</span>')+'<div class="grow"><b>'+esc(title)+'</b><small>'+esc(detail)+'</small></div>'+(status?badge(status):"")+'</div>'}
function heading(title,subtitle,action){return '<div class="heading"><div><div class="eyebrow">'+esc(organization()[1])+' · Quality CRM</div><h1>'+title+'</h1><p>'+subtitle+'</p></div><div class="row">'+(action||"")+'</div></div>'}
function button(text,page,alt){return '<button class="btn '+(alt?"alt":"")+'" data-go="'+page+'">'+text+'</button>'}
function banner(){const x=state.steps.find(s=>s[4]==="Waiting");return '<div class="alert"><span class="alert-circle">'+fa("hourglass-half")+'</span><div style="flex:1;min-width:0"><h3>'+(x?"Current holdup: Waiting on "+esc(x[1])+" for "+esc(x[0].toLowerCase())+".":"All outstanding handoffs have been cleared.")+'</h3><p>'+(x?"Next step: "+esc(x[2])+" can proceed after the requested item is provided.":"Review the next contractual milestone.")+'</p></div>'+badge(x?"Awaiting Title":"On Track")+'</div>'}
function completion(){return state.steps.filter(x=>x[4]==="Complete").length}
function progress(){return '<div class="progress">'+state.steps.map(x=>'<div class="'+(x[4]==="Complete"?"done":x[4]==="Waiting"?"now":"")+'"><i>'+(x[4]==="Complete"?"✓":"")+'</i><span>'+esc(x[0])+'</span></div>').join("")+'</div>'}
function hero(){return '<div class="panel property"><img alt="Actual listing exterior at 7169 Canyon Dr" src="'+PROPERTY+'"><div><div class="eyebrow">Example buyer transaction · Real listing photo</div><h2>7169 Canyon Dr, Park City, Utah</h2><p>The progress and participants are FICTIONAL demo content; not a real sale or contract.</p><div class="property-meta"><div><small>Current phase</small><b>Title / Settlement</b></div><div><small>Milestones complete</small><b>'+completion()+' / '+state.steps.length+'</b></div><div><small>Status</small>'+badge("Awaiting Title")+'</div></div>'+progress()+'<div class="row">'+button(fa("mobile-screen")+" Open Client Experience","portal")+button("Full Transaction Trail","transactions",true)+'</div></div></div>'}
function team(){return people.map(x=>row(x[0],x[1]+" · "+x[2],x[3]==="EC"?"Waiting":x[3]==="LO"?"In Process":"Active",x[3])).join("")}
function docList(){return [["Purchase Agreement","Complete"],["Earnest Money Receipt","Complete"],["Seller Disclosures","Complete"],["Inspection Report","Complete"],["Appraisal Review","Complete"],["Title Commitment","Complete"],["Final Settlement Figures","Waiting"],["Closing Disclosure","Upcoming"],["Closing Signatures","Upcoming"]].map(x=>row(x[0],x[1]==="Waiting"?"Requested from title / escrow":"Document milestone · demo only",x[1],"")).join("")}
function metric(label,num,sub){return '<div class="metric"><small>'+label+'</small><b>'+num+'</b><small>'+sub+'</small></div>'}
function dashboard(){return heading("Real Estate Command Center","Transactions, leads, and progress in one beautiful workspace.",button("Marketing Studio →","marketing",true))+banner()+hero()+'<div class="section"><h2>Today at a glance</h2><small class="small">Illustrative metrics</small></div><div class="grid4">'+metric("Hot leads","7","Sample leads")+metric("Transactions","3","One pending handoff")+metric("Tasks","2","Open assignments")+metric("Tour reports","4","Demo analytics")+'</div><div class="section"><h2>Transaction intelligence</h2></div><div class="grid2"><div class="panel"><div class="section"><h3>Transaction Team</h3>'+button("Client View →","portal",true)+'</div>'+team()+'</div><div class="panel"><div class="section"><h3>Documents</h3>'+button("View all →","documents",true)+'</div>'+docList()+'</div></div><div class="panel" style="margin-top:15px"><div class="section"><h3>Transactions</h3>'+button("View all →","transactions",true)+'</div>'+txTable()+'</div>'}
function txTable(){return '<div class="scroll"><table><thead><tr><th>Property / Scenario</th><th>Client side</th><th>Agent</th><th>Status</th><th></th></tr></thead><tbody>'+[["7169 Canyon Dr · Park City","Buyer","Awaiting Title"],["Example Deer Valley residence","Seller","Closed"],["Example Salt Lake property","Buyer","Closed"]].map(x=>'<tr><td><b>'+x[0]+'</b><br><small>Fictional transaction</small></td><td>'+x[1]+'</td><td>Adam Griffee · example only</td><td>'+badge(x[2])+'</td><td>'+button("Review →","transactions",true)+'</td></tr>').join("")+'</tbody></table></div>'}
function roadmap(){return '<div class="steps">'+state.steps.map((s,i)=>'<div class="step '+(s[4]==="Complete"?"done":s[4]==="Waiting"?"waiting":"")+'"><div class="stepnum">'+(s[4]==="Complete"?"✓":i+1)+'</div><div class="inner"><div class="row" style="justify-content:space-between"><strong>'+esc(s[0])+'</strong>'+badge(s[4])+'</div><p>'+esc(s[5])+'</p><small>Accountable: '+esc(s[1])+' · Waiting on: '+esc(s[2])+' · Document/action: '+esc(s[3])+'</small><div class="row" style="margin-top:10px"><button class="btn alt mini" data-step="'+i+'">Change status</button><button class="btn alt mini" data-remind="'+i+'">Preview reminder</button></div></div></div>').join("")+'</div>'}
function transactions(){return heading("Transaction Accountability","Every handoff has an owner, a dependency, and a next step.",button("Open Client App →","portal"))+banner()+'<div class="grid2"><div class="panel"><h3>Transaction journey</h3><p>Sample workflow only. Utah contract dates and obligations vary by signed agreement.</p>'+roadmap()+'</div><div class="panel"><h3>Who is responsible?</h3>'+team()+'<div class="notice">Clients see only permitted information, not private lender files or other parties confidential documents.</div></div></div>'}
function clientBody(){const tabs=[["timeline","Timeline"],["actions","My Actions"],["documents","Documents"],["team","My Team"],["messages","Messages"],["closing","Closing"]];let content="";
 if(state.tab==="timeline")content=roadmap();
 if(state.tab==="actions")content='<h3>Waiting on whom?</h3>'+state.steps.filter(x=>x[4]==="Waiting").map(x=>row(x[0],"Responsible: "+x[1]+" · Awaited by: "+x[2],"Waiting","")).join("")+'<p>You will be notified when it is your turn to act.</p>';
 if(state.tab==="documents")content=docList()+'<input type="file" class="input" id="upload" aria-label="Select a sample document"><p>File selection only. No upload is performed.</p>';
 if(state.tab==="team")content=team();
 if(state.tab==="messages")content='<h3>Message your agent</h3><textarea id="message" class="input" rows="4" placeholder="Ask your agent a question..."></textarea><button class="btn" id="draftMessage">Preview message</button><p>No real messages are sent.</p>';
 if(state.tab==="closing")content=state.steps.slice(-4).map(x=>row(x[0],x[5],x[4],"")).join("");
 return '<div class="tabs">'+tabs.map(x=>'<button data-tab="'+x[0]+'" class="'+(state.tab===x[0]?"active":"")+'">'+x[1]+'</button>').join("")+'</div>'+content;
}
function clientPortal(){return heading("Client Mobile Experience","A customer-friendly app, shown inside a phone frame.",'<button class="btn alt" id="clientLoginLink">Open client login ↗</button>')+'<div class="grid2"><div class="phone-wrap"><div class="phone"><div class="notch"></div><div class="phone-body"><div class="row"><img src="'+ZEN+'" width="35" height="35" alt="Properties Zen"><div style="flex:1"><b>Properties Zen</b><small style="display:block">Powered by Quality CRM</small></div><small>Jamie Davis · Buyer</small></div><div style="height:10px"></div>'+banner()+'<div class="panel"><img src="'+PROPERTY+'" alt="Park City property" style="width:100%;height:135px;object-fit:cover;border-radius:9px"><h3>7169 Canyon Dr</h3><p>Park City, Utah · Example purchase</p>'+progress()+'</div><div class="panel"><h3>What happens next?</h3><p>We are waiting on title/escrow for the final settlement figures. Your lender separately manages the Closing Disclosure.</p><div class="phone-actions">'+button("Timeline","clienttab:timeline",true)+button("My Actions","clienttab:actions",true)+button("Documents","clienttab:documents",true)+button("Message Team","clienttab:messages",true)+'</div></div><div class="panel">'+clientBody()+'</div></div></div></div><div><div class="panel"><h2>Less Stress. More Home.</h2><p>Buyer and seller access should never feel like a complex agent CRM.</p>'+row("Clear accountability","Know exactly who is waiting on what","Visible","")+row("Documents and signatures","One secure, permissioned location","Planned","")+row("Conversation with your team","Message the right professional","Planned","")+row("Real-time updates","Be informed at every milestone","Planned","")+'<button class="btn" id="launchClient">Try Client-Only Portal</button></div></div></div>'}
function clientOnly(){return '<div class="topbar"><img src="'+ZEN+'" width="45" alt="Properties Zen"><b style="flex:1">Properties Zen · Client Account</b><button class="btn alt mini" id="exitClient">Exit Client Demo</button></div><main class="content" style="max-width:950px;margin:auto">'+heading("Welcome home, Jamie.","Your progress, responsibilities, team and documents are right here.")+banner()+'<div class="panel"><img src="'+PROPERTY+'" alt="7169 Canyon Dr" style="width:100%;max-height:225px;object-fit:cover;border-radius:10px"><h2>7169 Canyon Dr, Park City, Utah</h2>'+progress()+'</div><div class="panel" style="margin-top:14px">'+clientBody()+'</div></main>'}
function marketing(){let chosen=comps.filter((x,i)=>state.selected.includes(i));let avg=chosen.length?chosen.reduce((a,x)=>a+x[2],0)/chosen.length:0;const tools=[["house-circle-check","CMAs","Seller pricing and comparable analysis"],["chart-line","Property Tour Analytics","Views and engagement"],["arrow-trend-up","Market Intelligence","Area reports and trends"],["video","Listing Reels","Property video content"],["envelope","Email Campaigns","Nurture workflows"],["share-nodes","Print + Social","Marketing assets"]];
 const cards='<div class="features">'+tools.map(x=>'<button class="feature" data-feature="'+x[1]+'"><i class="fa-solid fa-'+x[0]+'"></i><span><b>'+x[1]+'</b><small>'+x[2]+'</small></span></button>').join("")+'</div>';
 const compsHTML=comps.map((x,i)=>'<label class="list-item"><input type="checkbox" data-comp="'+i+'" '+(state.selected.includes(i)?"checked":"")+'><div class="grow"><b>'+x[0]+'</b><small>FICTIONAL · '+x[1]+' sq ft</small></div><strong>'+money(x[2])+'</strong></label>').join("");
 const chart='<div class="chart">'+[35,60,44,80,64,95,49,72,86,57,93].map(x=>'<div style="height:'+x+'%"></div>').join("")+'</div>';
 return heading("Marketing Studio","Build CMAs, property tour analytics and other listing marketing.",button("Transactions →","transactions",true))+cards+'<div class="grid2"><div class="panel"><h3>Create CMA</h3><p>Select fictional comparable sales to demonstrate the workflow. No MLS data is connected.</p><div class="field"><label>Subject property</label><input class="input" id="address" value="7169 Canyon Dr, Park City, UT"></div><div class="row"><img src="'+PROPERTY+'" width="125" height="93" style="object-fit:cover;border-radius:10px" alt="Real 7169 Canyon Dr photo"><div><b>7169 Canyon Dr</b><p>Actual listing imagery.<br>Sample comps below are not verified sales.</p></div></div><div class="section"><h3>Illustrative comparables</h3><small>'+chosen.length+' selected</small></div>'+compsHTML+'<div class="notice"><div class="grid3"><div>Low<br><b>'+(chosen.length?money(Math.min(...chosen.map(x=>x[2]))):"—")+'</b></div><div>Arithmetic mean<br><b>'+(chosen.length?money(avg):"—")+'</b></div><div>High<br><b>'+(chosen.length?money(Math.max(...chosen.map(x=>x[2]))):"—")+'</b></div></div><p>This is not a valuation estimate or appraisal.</p></div><button class="btn" id="makeCMA" '+(!chosen.length?"disabled":"")+'>Generate Sample CMA Report</button></div><div class="panel"><h3>Property Tour Analytics</h3><p>Example visitor and engagement report for the property tour.</p><div class="grid3">'+metric("Tour Views","1,248","Sample")+metric("Unique Visitors","183","Sample")+metric("Leads Generated","36","Sample")+'</div><div class="section"><b>Tour traffic over time</b></div>'+chart+row("Info requests","24 sample conversions","","")+row("Showings scheduled","18 sample conversions","","")+row("Property saved","32 sample actions","","")+'<button class="btn" id="tourReport" style="margin-top:14px">Generate Sample Tour Report</button></div></div><div class="section"><h2>Generated demo reports</h2></div><div class="panel"><div id="generated">'+(state.reports.length?state.reports.map(x=>row(x,"Created in current demo session","Sample","")).join(""):'<p>Generate a CMA or tour report to see an editable preview.</p>')+'</div></div>'}
function leads(hot){const data=[["Jordan Parker","Park City buyer","Hot"],["Morgan Lee","Luxury seller","Hot"],["Taylor Brooks","Investor","Nurturing"],["Alex Rivera","Relocation","Hot"]].filter(x=>!hot||x[2]==="Hot");return heading(hot?"Hot Leads":"Lead Management","Priority follow-up, lead sources, and agent accountability.")+'<div class="panel"><table><thead><tr><th>Contact</th><th>Intent</th><th>Status</th><th>Action</th></tr></thead><tbody>'+data.map(x=>'<tr><td>'+x[0]+'</td><td>'+x[1]+'</td><td>'+badge(x[2])+'</td><td><button class="btn alt mini" data-lead="'+x[0]+'">View 360°</button></td></tr>').join("")+'</tbody></table><p>Sample names only. No connected lead database.</p></div>'}
function calendar(){return heading("Calendar","Deadlines, showings, appointments, and scheduling.")+'<div class="grid2"><div class="panel"><h3>October 2026 · Example agenda</h3>'+row("Oct 8","Team project review","Today","")+row("Oct 9","Buyer transaction check-in","Upcoming","")+row("Oct 12","Closing preparation call","Upcoming","")+'</div><div class="panel"><h3>Upcoming transaction steps</h3>'+state.steps.slice(-4).map(x=>row(x[0],x[1],x[4],"")).join("")+'<p>No external calendar sync is connected.</p></div></div>'}
function tasks(){return heading("My Tasks","Clearly assigned to people and organizations.",'<button class="btn" id="addTask">Add Task</button>')+'<div class="panel">'+state.tasks.map((t,i)=>'<label class="list-item"><input type="checkbox" data-task="'+i+'" '+(t.done?"checked":"")+'><div class="grow"><b style="'+(t.done?"text-decoration:line-through;opacity:.5":"")+'">'+esc(t.t)+'</b><small>Adam Griffee · Properties Zen</small></div>'+badge(t.done?"Complete":"Upcoming")+'</label>').join("")+'</div>'}
function inbox(sms){return heading(sms?"SMS Messages":"Unified Mail Inbox","Account-specific communications with clear sender identity.")+'<div class="grid2"><div class="panel"><h3>Sample messages</h3>'+row("Title Company","Settlement figures requested","Waiting","")+row("Buyer","Question about next steps","Unread","")+row("Lender","Closing document coordination","Upcoming","")+'</div><div class="panel"><h3>Draft '+(sms?"SMS":"Email")+'</h3><p>From: Properties Zen · sample sender identity</p><textarea id="draft" class="input" rows="5" placeholder="Compose message..."></textarea><button class="btn" id="previewDraft">Preview · Do Not Send</button><div class="notice">Messages are never sent from the public demo.</div></div></div>'}
function dialer(){return heading("Business Dialer","A dialer with per-business caller ID and call analytics.")+'<div class="grid2"><div class="panel" style="max-width:410px"><h3>Phone Dialer</h3><p>Dial out as: Properties Zen · demonstration</p><input class="input" id="phonenumber" value="'+esc(state.phone)+'" placeholder="+1 (___) ___-____"><div class="grid3" style="margin-top:13px">'+["1","2","3","4","5","6","7","8","9","*","0","#"].map(x=>'<button class="btn alt" data-digit="'+x+'" style="font-size:20px">'+x+'</button>').join("")+'</div><button class="btn" id="call" style="margin-top:14px;width:100%">Preview Call</button><p>No actual calls are placed.</p></div><div class="panel"><h3>Call Dashboard</h3>'+metric("Answered Calls","21","Example")+metric("Connected Leads","8","Example")+'<p>Provider integration is not connected.</p></div></div>'}
function card(){return heading("Properties Zen Business Card","Live preview using the verified WordPress headshot.")+'<div class="grid2"><div class="panel" style="display:flex;justify-content:center;background:#f7f6f1"><div class="card-preview"><img class="portrait" src="'+HEADSHOT+'" alt="Actual Adam Griffee"><img src="'+ZEN+'" alt="Properties Zen" width="52"><h2>Adam Griffee</h2><p>REALTOR® | ASSOCIATE BROKER</p><div class="bottom"><h3>PROPERTIES ZEN</h3><small>Powered by Quality CRM</small><p>Park City & Salt Lake Luxury Real Estate<br>(801) 856-0991<br>AdamGriffee.com<br>LIC# 5505741-AB00</p></div></div></div><div class="panel"><h3>Photo source verified</h3><p>This image is sourced directly from AdamGriffee.com via its WordPress media library. No generated person is used.</p><p>Business card is an HTML prototype; professional print artwork and a verified contact QR remain separate deliverables.</p><button class="btn alt" id="print">Print preview</button></div></div>'}
function generic(){return heading(menu.find(x=>x[0]===state.page)?.[2]||organization()[1],organization()[3])+ '<div class="panel"><h3>Module preview</h3><p>Available under the Quality CRM operating system as a planned workspace-specific module.</p>'+button("Explore Marketing →","marketing")+'</div>'}
function orgDashboard(){return heading(organization()[1],organization()[3])+'<div class="panel"><h2>Quality CRM connected workspace concept</h2><p>This workspace is listed but is not connected to its production systems.</p><div class="features">'+[["Projects","tasks"],["CRM","leads"],["Websites","websites"],["Reporting","reports"],["Communications","inbox"],["Marketing","marketing"]].map(x=>'<button class="feature" data-go="'+x[1]+'"><i class="fa-solid fa-grip"></i><b>'+x[0]+'</b></button>').join("")+'</div></div>'}
function view(){if(state.page==="dashboard")return ["zen","adam","luxury"].includes(state.org)?dashboard():orgDashboard();if(state.page==="transactions")return transactions();if(state.page==="portal")return clientPortal();if(state.page==="marketing")return marketing();if(state.page==="hot"||state.page==="leads")return leads(state.page==="hot");if(state.page==="calendar")return calendar();if(state.page==="tasks")return tasks();if(state.page==="inbox"||state.page==="sms")return inbox(state.page==="sms");if(state.page==="dialer")return dialer();if(state.page==="cards")return card();return generic()}
function shell(){const o=organization();return '<div class="app"><div class="cover" id="cover"></div><aside class="sidebar" id="sidebar"><div class="brand"><img src="'+logo()+'" alt="'+esc(o[1])+' logo"><strong>'+esc(o[1])+'</strong><small>'+(state.org==="quality"?"Your universal workspace":"Powered by Quality CRM")+'</small></div><nav class="side-nav">'+menu.map(x=>'<button data-go="'+x[0]+'" class="'+(state.page===x[0]?"active":"")+'"><i class="fa-solid fa-'+x[1]+'"></i>'+x[2]+'</button>').join("")+'</nav><div class="side-tagline">'+(state.org==="zen"?"Less Stress.<br>More Home.":"Every Business.<br>One Q.")+'</div></aside><div class="main"><header class="topbar"><button class="btn alt menubtn" id="toggle"><i class="fa-solid fa-bars"></i></button><div class="top-search">'+fa("magnifying-glass")+'<input placeholder="Search clients, properties, documents..." aria-label="Search"></div><select class="workspace" id="workspace" aria-label="Switch workspace">'+organizations.map(x=>'<option value="'+x[0]+'" '+(state.org===x[0]?"selected":"")+'>'+x[1]+'</option>').join("")+'</select><div class="person"><img src="'+HEADSHOT+'" alt="Actual Adam Griffee headshot"><span><b>Adam Griffee</b><small>Realtor · Associate Broker</small></span></div><button class="btn alt mini" id="logout" aria-label="Exit demo"><i class="fa-solid fa-right-from-bracket"></i></button></header><div class="content"><div class="demo">Interactive concept using fictional CRM data. Listing photo and Adam headshot from verified WordPress media; no real transaction, contact, valuation, messages, or signatures.</div>'+view()+'</div></div></div>'}
function clientOnly(){return '<header class="topbar"><img src="'+ZEN+'" width="43" alt="Properties Zen"><b style="flex:1">Properties Zen · Client</b><button class="btn alt mini" id="exitClient">Exit client demo</button></header><div class="content" style="max-width:1000px;margin:auto">'+heading("Welcome home, Jamie.","Your transaction, team, and next actions — all in one place.")+banner()+'<div class="panel"><img src="'+PROPERTY+'" style="width:100%;max-height:255px;object-fit:cover;border-radius:9px" alt="Property"><h2>7169 Canyon Dr, Park City</h2>'+progress()+'</div><div class="panel" style="margin-top:15px">'+clientBody()+'</div></div>'}
function login(){const client=state.role==="client";return '<div class="login"><div class="loginbox"><img src="'+(client?ZEN:Q)+'" alt="Quality CRM"><h1>'+(client?"Properties Zen":"Quality CRM")+'</h1><p>'+(client?"Welcome Home · Client Experience":"One login. Every business. One Q.")+'</p><div class="notice">Public demo only. This is not secure authentication; no data is protected by these sample credentials.</div><div class="field"><label>Demo username</label><input class="input" id="username" value="'+(client?"buyer.demo":"adam.demo")+'"></div><div class="field"><label>Demo password</label><input class="input" id="password" value="demo2026" type="text"></div><button class="btn" id="login" style="width:100%">Open '+(client?"Client":"Agent")+' Demo</button><button class="btn alt" style="width:100%;margin-top:10px" id="swap">Switch to '+(client?"Agent":"Client")+' Demo</button></div></div>'}
function toast(text){const el=document.getElementById("toast");el.textContent=text;el.style.display="block";clearTimeout(window.toastTimeout);window.toastTimeout=setTimeout(()=>el.style.display="none",3000)}
function popup(title,body,action,fn){document.getElementById("modalTitle").textContent=title;document.getElementById("modalBody").innerHTML=body;document.getElementById("modalConfirm").textContent=action||"Confirm";document.getElementById("modalConfirm").onclick=()=>{document.getElementById("modalbg").classList.remove("open");fn?.()};document.getElementById("modalbg").classList.add("open")}
function go(page){if(page.startsWith("clienttab:")){state.tab=page.split(":")[1];state.page="portal"}else state.page=page;document.getElementById("sidebar")?.classList.remove("open");document.getElementById("cover")?.classList.remove("open");location.hash=state.page;render()}
function report(name){const chosen=comps.filter((x,i)=>state.selected.includes(i)),avg=chosen.length?chosen.reduce((a,x)=>a+x[2],0)/chosen.length:0;state.reports.unshift(name+" · 7169 Canyon Dr · sample only");popup(name+" · Illustrative Report",'<p>Subject: 7169 Canyon Dr, Park City</p><p>Selected fictional comparables: '+chosen.length+'. Arithmetic mean: '+money(avg)+'.</p><p>This is a demonstration, not a CMA, appraisal, or live tour report. Actual analysis requires licensed MLS data, adjustments and professional review.</p>',"Close",()=>{render()})}
function render(){document.getElementById("root").innerHTML=!state.login?login():state.role==="client"?clientOnly():shell();bind()}
function bind(){
 document.querySelectorAll("[data-go]").forEach(x=>x.onclick=()=>go(x.dataset.go));
 document.querySelectorAll("[data-tab]").forEach(x=>x.onclick=()=>{state.tab=x.dataset.tab;render()});
 document.querySelectorAll("[data-step]").forEach(x=>x.onclick=()=>{const i=+x.dataset.step,s=state.steps[i];popup("Update: "+s[0],'<p>Responsible: '+s[1]+'; awaiting: '+s[2]+'</p><select id="statusSelect" class="input">'+["Complete","Waiting","Upcoming"].map(z=>'<option '+(s[4]===z?"selected":"")+'>'+z+'</option>').join("")+'</select>',"Update example",()=>{s[4]=document.getElementById("statusSelect")?.value||"Complete";render();toast("Sample milestone updated; no messages sent.")})});
 document.querySelectorAll("[data-remind]").forEach(x=>x.onclick=()=>{const s=state.steps[+x.dataset.remind];popup("Preview reminder",'<p>To: '+s[1]+'</p><p>We are waiting on '+s[0]+'; requested item: '+s[3]+'.</p><p>No message will be sent.</p>',"Close",()=>{})});
 document.querySelectorAll("[data-comp]").forEach(x=>x.onchange=ev=>{const i=+x.dataset.comp;state.selected=ev.target.checked?[...state.selected,i]:state.selected.filter(v=>v!==i);render()});
 document.querySelectorAll("[data-task]").forEach(x=>x.onchange=ev=>{state.tasks[+x.dataset.task].done=ev.target.checked;render()});
 document.querySelectorAll("[data-feature]").forEach(x=>x.onclick=()=>toast(x.dataset.feature+" · sample marketing module"));
 document.querySelectorAll("[data-lead]").forEach(x=>x.onclick=()=>popup("Contact 360° · "+x.dataset.lead,"<p>Timeline, conversations, notes, transactions, appointments and documents would be shown here.</p>","Close",()=>{}));
 document.querySelectorAll("[data-digit]").forEach(x=>x.onclick=()=>{const input=document.getElementById("phonenumber");if(input){input.value+=x.dataset.digit;state.phone=input.value}});
 const events={
 workspace:el=>el.onchange=ev=>{state.org=ev.target.value;state.page="dashboard";document.documentElement.style.setProperty("--teal",organization()[2]);render()},
 toggle:el=>el.onclick=()=>{document.getElementById("sidebar").classList.add("open");document.getElementById("cover").classList.add("open")},
 cover:el=>el.onclick=()=>{document.getElementById("sidebar").classList.remove("open");el.classList.remove("open")},
 logout:el=>el.onclick=()=>{state.login=false;render()},
 login:el=>el.onclick=()=>{const u=document.getElementById("username").value.toLowerCase(),p=document.getElementById("password").value;if(u===(state.role==="client"?"buyer.demo":"adam.demo")&&p==="demo2026"){state.login=true;state.org="zen";state.page="dashboard";render()}else toast("Use the displayed public demo credentials.")},
 swap:el=>el.onclick=()=>{state.role=state.role==="client"?"agent":"client";render()},
 clientLoginLink:el=>el.onclick=()=>window.open(location.pathname+"?role=client&login=1","_blank"),
 launchClient:el=>el.onclick=()=>{state.role="client";state.login=false;render()},
 exitClient:el=>el.onclick=()=>{state.role="agent";state.login=false;render()},
 addTask:el=>el.onclick=()=>popup("New task",'<input class="input" id="newTask" placeholder="Task description">',"Add",()=>{const t=document.getElementById("newTask")?.value.trim();if(t)state.tasks.unshift({t,done:false});render()}),
 previewDraft:el=>el.onclick=()=>popup("Message preview",'<p>'+esc(document.getElementById("draft").value)+'</p><p>NOT SENT.</p>',"Close",()=>{}),
 draftMessage:el=>el.onclick=()=>popup("Message preview",'<p>'+esc(document.getElementById("message").value)+'</p><p>NOT SENT.</p>',"Close",()=>{}),
 makeCMA:el=>el.onclick=()=>report("Comparative Market Analysis"),
 tourReport:el=>el.onclick=()=>report("Property Tour Analytics"),
 call:el=>el.onclick=()=>toast("No call placed. This is a public demo."),
 print:el=>el.onclick=()=>window.print()
 };
 Object.keys(events).forEach(id=>{const el=document.getElementById(id);if(el)events[id](el)});
}
document.getElementById("modalCancel").onclick=()=>document.getElementById("modalbg").classList.remove("open");
document.getElementById("modalbg").onclick=ev=>{if(ev.target.id==="modalbg")ev.target.classList.remove("open")};
const query=new URLSearchParams(location.search);
state.role=query.get("role")==="client"?"client":"agent";
state.login=query.get("login")!=="1";
if(organizations.some(x=>x[0]===query.get("workspace")))state.org=query.get("workspace");
const hash=location.hash.slice(1);
if(menu.some(x=>x[0]===hash))state.page=hash;
render();
